2024-02-13T22:21:57.819873Z [info     ] Could not append type because the JSON schema for the dictionary `{'oneOf': [{'type': ['number']}, {'type': ['string']}, {'type': ['boolean']}]}` appears to be invalid. cmd_type=elb consumer=False name=tap-csv producer=True stdio=stderr string_id=tap-csv
2024-02-13T22:21:57.820837Z [info     ] Could not append type because the JSON schema for the dictionary `{'oneOf': [{'type': ['string']}, {'type': 'array', 'items': {'type': ['string']}}]}` appears to be invalid. cmd_type=elb consumer=False name=tap-csv producer=True stdio=stderr string_id=tap-csv
2024-02-13T22:21:57.937566Z [info     ] 2024-02-13 19:21:57,937 | INFO     | tap-csv.order_details | Beginning full_table sync of 'order_details'... cmd_type=elb consumer=False name=tap-csv producer=True stdio=stderr string_id=tap-csv
2024-02-13T22:21:57.938327Z [info     ] 2024-02-13 19:21:57,937 | INFO     | tap-csv.order_details | Tap has custom mapper. Using 1 provided map(s). cmd_type=elb consumer=False name=tap-csv producer=True stdio=stderr string_id=tap-csv
2024-02-13T22:21:58.301025Z [info     ] 2024-02-13 19:21:58,300 | INFO     | target-postgres      | Target 'target-postgres' is listening for input from tap. cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.301705Z [info     ] 2024-02-13 19:21:58,301 | INFO     | target-postgres      | Initializing 'target-postgres' target sink... cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.302251Z [info     ] 2024-02-13 19:21:58,301 | INFO     | target-postgres.order_details | Initializing target sink for stream 'order_details'... cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.405823Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.406417Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.406897Z [info     ]     self._dbapi_connection = engine.raw_connection() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.407349Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.407788Z [info     ]     return self.pool.connect() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.408191Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.408586Z [info     ]     return _ConnectionFairy._checkout(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.408976Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.409388Z [info     ]     fairy = _ConnectionRecord.checkout(pool) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.409775Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 712, in checkout cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.410177Z [info     ]     rec = pool._do_get()       cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.410574Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.410967Z [info     ]     self._dec_overflow()       cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.411361Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.411766Z [info     ]     raise exc_value.with_traceback(exc_tb) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.412155Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.412538Z [info     ]     return self._create_connection() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.412925Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.413385Z [info     ]     return _ConnectionRecord(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.413782Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 674, in __init__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.414187Z [info     ]     self.__connect()           cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.414583Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in __connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.414986Z [info     ]     pool.logger.debug("Error on connect(): %s", e) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.415377Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.415780Z [info     ]     raise exc_value.with_traceback(exc_tb) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.416171Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 896, in __connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.416572Z [info     ]     self.dbapi_connection = connection = pool._invoke_creator(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.417025Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 643, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.417422Z [info     ]     return dialect.connect(*cargs, **cparams) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.417824Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 616, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.418215Z [info     ]     return self.loaded_dbapi.connect(*cargs, **cparams) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.418604Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.418990Z [info     ]     conn = _connect(dsn, connection_factory=connection_factory, **kwasync) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.419401Z [info     ] psycopg2.OperationalError: could not translate host name "db_source" to address: Name or service not known cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.419791Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.420174Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.420548Z [info     ] The above exception was the direct cause of the following exception: cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.420930Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.421329Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.421718Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module> cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.422108Z [info     ]     sys.exit(TargetPostgres.cli()) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.422504Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.422888Z [info     ]     return self.main(*args, **kwargs) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.423270Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.423646Z [info     ]     rv = self.invoke(ctx)      cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.424038Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/plugin_base.py", line 105, in invoke cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.424441Z [info     ]     return super().invoke(ctx) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.424839Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.425284Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.425714Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.426121Z [info     ]     return __callback(*args, **kwargs) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.426532Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 554, in invoke cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.427407Z [info     ]     target.listen(file_input)  cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.428224Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 36, in listen cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.428948Z [info     ]     self._process_lines(file_input) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.429737Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 295, in _process_lines cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.430676Z [info     ]     counter = super()._process_lines(file_input) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.431431Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/io_base.py", line 92, in _process_lines cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.431844Z [info     ]     self._process_schema_message(line_dict) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.432228Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 407, in _process_schema_message cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.432619Z [info     ]     _ = self.get_sink(         cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.433101Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 767, in get_sink cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.433764Z [info     ]     return self.add_sqlsink(stream_name, schema, key_properties) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.434453Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/target_base.py", line 701, in add_sqlsink cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.435115Z [info     ]     sink.setup()               cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.435857Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/sinks.py", line 56, in setup cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.436573Z [info     ]     self.connector.prepare_schema(self.schema_name) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.437126Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py", line 757, in prepare_schema cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.437524Z [info     ]     schema_exists = self.schema_exists(schema_name) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.437910Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py", line 588, in schema_exists cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.438297Z [info     ]     sqlalchemy.inspect(self._engine).get_schema_names(), cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.438685Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/inspection.py", line 140, in inspect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.439073Z [info     ]     ret = reg(subject)         cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.439465Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 303, in _engine_insp cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.439872Z [info     ]     return Inspector._construct(Inspector._init_engine, bind) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.440442Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 236, in _construct cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.440891Z [info     ]     init(self, bind)           cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.442268Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 247, in _init_engine cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.442722Z [info     ]     engine.connect().close()   cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.443156Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3258, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.443620Z [info     ]     return self._connection_cls(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.444073Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.444525Z [info     ]     Connection._handle_dbapi_exception_noconnection( cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.444973Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2422, in _handle_dbapi_exception_noconnection cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.445417Z [info     ]     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.445811Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.446197Z [info     ]     self._dbapi_connection = engine.raw_connection() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.446857Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.447398Z [info     ]     return self.pool.connect() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.447834Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 449, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.448262Z [info     ]     return _ConnectionFairy._checkout(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.448670Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.449126Z [info     ]     fairy = _ConnectionRecord.checkout(pool) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.449522Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 712, in checkout cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.449919Z [info     ]     rec = pool._do_get()       cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.450313Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.450726Z [info     ]     self._dec_overflow()       cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.451122Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.451543Z [info     ]     raise exc_value.with_traceback(exc_tb) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.451936Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.452331Z [info     ]     return self._create_connection() cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.452724Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.453138Z [info     ]     return _ConnectionRecord(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.453538Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 674, in __init__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.453956Z [info     ]     self.__connect()           cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.454390Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 901, in __connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.454816Z [info     ]     pool.logger.debug("Error on connect(): %s", e) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.455236Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__ cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.455657Z [info     ]     raise exc_value.with_traceback(exc_tb) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.456068Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 896, in __connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.456486Z [info     ]     self.dbapi_connection = connection = pool._invoke_creator(self) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.456908Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 643, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.469057Z [info     ]     return dialect.connect(*cargs, **cparams) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.469589Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 616, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.470025Z [info     ]     return self.loaded_dbapi.connect(*cargs, **cparams) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.470422Z [info     ]   File "/home/kirillov/code-challenge/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.470819Z [info     ]     conn = _connect(dsn, connection_factory=connection_factory, **kwasync) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.471239Z [info     ] sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db_source" to address: Name or service not known cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.471746Z [info     ]                                cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:58.472264Z [info     ] (Background on this error at: https://sqlalche.me/e/20/e3q8) cmd_type=elb consumer=True name=target-postgres producer=False stdio=stderr string_id=target-postgres
2024-02-13T22:21:59.065080Z [error    ]
Traceback (most recent call last):
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/logging/output_logger.py", line 207, in redirect_logging
    yield
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 467, in run
    await self.run_with_job()
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 499, in run_with_job
    await self.execute()
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 459, in execute
    await manager.run()
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 664, in run
    await self._wait_for_process_completion(self.elb.head)
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/block/extract_load.py", line 737, in _wait_for_process_completion
    raise output_futures_failed.exception()  # noqa: RSE102
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/logging/utils.py", line 237, in capture_subprocess_output
    if not await _write_line_writer(writer, line):
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/logging/utils.py", line 205, in _write_line_writer
    await writer.wait_closed()
  File "/usr/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/home/kirillov/.local/lib/python3.8/site-packages/meltano/core/logging/utils.py", line 203, in _write_line_writer
    await writer.drain()
  File "/usr/lib/python3.8/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.8/asyncio/streams.py", line 197, in _drain_helper
    await waiter
BrokenPipeError
